In [1]:
import numpy as np
import pandas as pd

In [10]:
df=pd.read_csv('C:\\Users\\prave\\Downloads\\artwork_data.csv',index_col='id',usecols=['id','artist'])
print(df)

                    artist
id
1035         Blake, Robert
1036         Blake, Robert
1037         Blake, Robert
1038         Blake, Robert
1039        Blake, William
...                    ...
122960  P-Orridge, Genesis
122961  P-Orridge, Genesis
121181        Hatoum, Mona
112306       Creed, Martin
127035   Brunias, Agostino

[69201 rows x 1 columns]

In [13]:
df.to_pickle('C:\Hepsibha\python class 2020\dataframe1.pickle')#pickle is a defult serialization format

In [15]:
df2=pd.read_pickle("C:\Hepsibha\python class 2020\dataframe1.pickle")

print(df2)

                    artist
id
1035         Blake, Robert
1036         Blake, Robert
1037         Blake, Robert
1038         Blake, Robert
1039        Blake, William
...                    ...
122960  P-Orridge, Genesis
122961  P-Orridge, Genesis
121181        Hatoum, Mona
112306       Creed, Martin
127035   Brunias, Agostino

[69201 rows x 1 columns]

In [16]:
introducing to indexing and filttering in pandas:
    1.how many distinct artist are there in the data set?
    2.how many atworks by blake,william are there?
    3.what is the art work with the biggest dimensions?

SyntaxError: invalid syntax (<ipython-input-16-90e73c58654d>, line 1)

In [17]:
df=pd.read_csv('C:\\Users\\prave\\Downloads\\artwork_data.csv')
df

C:\Users\prave\Anaconda3n\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (9,13) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826â€“7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69196,122960,T13865,"P-Orridge, Genesis",artist,16646,Larvae (from Tampax Romana),1975,"Perspex, Wood, hairpiece, tampon and human blood",Transferred from Tate Archive 2012,1975,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69197,122961,T13866,"P-Orridge, Genesis",artist,16646,Living Womb (from Tampax Romana),1976,"Wood, Perspex, plastic, photograph on paper, t...",Transferred from Tate Archive 2012,1976,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69198,121181,T13867,"Hatoum, Mona",artist,2365,Present Tense,1996,Soap and glass beads,Presented by Tate Members 2013,1996,2013.0,displayed: 45 x 2410 x 2990 mm,45,2410,2990.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/hatoum-pre...
69199,112306,T13868,"Creed, Martin",artist,2760,Work No. 227: The lights going on and off,2000,Gallery lighting,"Purchased with funds provided by Tate Members,...",2000,2013.0,Overall display dimensions variable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/creed-work...
69200,127035,T13869,"Brunias, Agostino",artist,3824,Dancing Scene in the West Indies,1764â€“96,Oil paint on canvas,Purchased with assistance from Tate Patrons an...,1764,2013.0,unconfirmed: 508 x 660 mm,508,660,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/brunias-da...

In [18]:
artist=df['artist']

In [20]:
pd.unique(artist)

array(['Blake, Robert', 'Blake, William', 'Richmond, George', ...,
       'Sterne, Hedda', 'P-Orridge, Genesis', 'Brunias, Agostino'],
      dtype=object)

In [21]:
len(pd.unique(artist))

3336

In [22]:
s=df['artist']=='Bacon,Francis'
s.value_counts()

False    69201
Name: artist, dtype: int64

In [23]:
s=df['artist']=='blake,william'
s.value_counts()

False    69201
Name: artist, dtype: int64

In [ ]:
introduction to loc and iloc

loc----->lable(work with direct col names)
iloc----->position (working with indexing)

In [26]:
#df.loc[rowindex,colindex]
df.loc[1035,'artist']
df

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826â€“7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69196,122960,T13865,"P-Orridge, Genesis",artist,16646,Larvae (from Tampax Romana),1975,"Perspex, Wood, hairpiece, tampon and human blood",Transferred from Tate Archive 2012,1975,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69197,122961,T13866,"P-Orridge, Genesis",artist,16646,Living Womb (from Tampax Romana),1976,"Wood, Perspex, plastic, photograph on paper, t...",Transferred from Tate Archive 2012,1976,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69198,121181,T13867,"Hatoum, Mona",artist,2365,Present Tense,1996,Soap and glass beads,Presented by Tate Members 2013,1996,2013.0,displayed: 45 x 2410 x 2990 mm,45,2410,2990.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/hatoum-pre...
69199,112306,T13868,"Creed, Martin",artist,2760,Work No. 227: The lights going on and off,2000,Gallery lighting,"Purchased with funds provided by Tate Members,...",2000,2013.0,Overall display dimensions variable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/creed-work...
69200,127035,T13869,"Brunias, Agostino",artist,3824,Dancing Scene in the West Indies,1764â€“96,Oil paint on canvas,Purchased with assistance from Tate Patrons an...,1764,2013.0,unconfirmed: 508 x 660 mm,508,660,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/brunias-da...

In [28]:
df.iloc[100:300,[9,1,4]]
df

,id,accession_number,artist,artistRole,artistId,title,dateText,medium,creditLine,year,acquisitionYear,dimensions,width,height,depth,units,inscription,thumbnailCopyright,thumbnailUrl,url
0,1035,A00001,"Blake, Robert",artist,38,A Figure Bowing before a Seated Old Man with h...,date not known,"Watercolour, ink, chalk and graphite on paper....",Presented by Mrs John Richmond 1922,NaN,1922.0,support: 394 x 419 mm,394,419,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-a-fi...
1,1036,A00002,"Blake, Robert",artist,38,"Two Drawings of Frightened Figures, Probably f...",date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 311 x 213 mm,311,213,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-two-...
2,1037,A00003,"Blake, Robert",artist,38,The Preaching of Warning. Verso: An Old Man En...,?c.1785,Graphite on paper. Verso: graphite on paper,Presented by Mrs John Richmond 1922,1785,1922.0,support: 343 x 467 mm,343,467,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
3,1038,A00004,"Blake, Robert",artist,38,Six Drawings of Figures with Outstretched Arms,date not known,Graphite on paper,Presented by Mrs John Richmond 1922,NaN,1922.0,support: 318 x 394 mm,318,394,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-six-...
4,1039,A00005,"Blake, William",artist,39,The Circle of the Lustful: Francesca da Rimini...,"1826â€“7, reprinted 1892",Line engraving on paper,Purchased with the assistance of a special gra...,1826,1919.0,image: 243 x 335 mm,243,335,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/A/A00/A...,http://www.tate.org.uk/art/artworks/blake-the-...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69196,122960,T13865,"P-Orridge, Genesis",artist,16646,Larvae (from Tampax Romana),1975,"Perspex, Wood, hairpiece, tampon and human blood",Transferred from Tate Archive 2012,1975,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69197,122961,T13866,"P-Orridge, Genesis",artist,16646,Living Womb (from Tampax Romana),1976,"Wood, Perspex, plastic, photograph on paper, t...",Transferred from Tate Archive 2012,1976,2013.0,object: 305 x 305 x 135 mm,305,305,135.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/p-orridge-...
69198,121181,T13867,"Hatoum, Mona",artist,2365,Present Tense,1996,Soap and glass beads,Presented by Tate Members 2013,1996,2013.0,displayed: 45 x 2410 x 2990 mm,45,2410,2990.0,mm,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/hatoum-pre...
69199,112306,T13868,"Creed, Martin",artist,2760,Work No. 227: The lights going on and off,2000,Gallery lighting,"Purchased with funds provided by Tate Members,...",2000,2013.0,Overall display dimensions variable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,http://www.tate.org.uk/art/artworks/creed-work...
69200,127035,T13869,"Brunias, Agostino",artist,3824,Dancing Scene in the West Indies,1764â€“96,Oil paint on canvas,Purchased with assistance from Tate Patrons an...,1764,2013.0,unconfirmed: 508 x 660 mm,508,660,NaN,mm,NaN,NaN,http://www.tate.org.uk/art/images/work/T/T13/T...,http://www.tate.org.uk/art/artworks/brunias-da...

In [ ]:
Area=height*width

In [29]:
df['height']*df['width']

TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
#height and width cols

In [30]:
df['height'].sort_values().head()
df['height'].sort_values().tail()

TypeError: '<' not supported between instances of 'str' and 'float'

In [31]:
df['width'].sort_values().head()

62198           (1):
68540    (diameter):
2427         (each):
54196        (each):
67796       (image):
Name: width, dtype: object

In [32]:
df['width'].sort_values().tail()

69188    NaN
69190    NaN
69191    NaN
69193    NaN
69199    NaN
Name: width, dtype: object

In [34]:
pd.to_numeric(df['width'])

ValueError: Unable to parse string "(upper):" at position 1839

In [35]:
a=pd.to_numeric(df['width'],errors='coerce')
print(a)

0        394.0
1        311.0
2        343.0
3        318.0
4        243.0
         ...
69196    305.0
69197    305.0
69198     45.0
69199      NaN
69200    508.0
Name: width, Length: 69201, dtype: float64

In [36]:
a*b

NameError: name 'b' is not defined

In [37]:
b=pd.to_numeric(df['height'],errors='coerce')
print(b)

0         419.0
1         213.0
2         467.0
3         394.0
4         335.0
          ...
69196     305.0
69197     305.0
69198    2410.0
69199       NaN
69200     660.0
Name: height, Length: 69201, dtype: float64

In [38]:
a*b

0        165086.0
1         66243.0
2        160181.0
3        125292.0
4         81405.0
           ...
69196     93025.0
69197     93025.0
69198    108450.0
69199         NaN
69200    335280.0
Length: 69201, dtype: float64

In [39]:
area=a*b
print(area)

0        165086.0
1         66243.0
2        160181.0
3        125292.0
4         81405.0
           ...
69196     93025.0
69197     93025.0
69198    108450.0
69199         NaN
69200    335280.0
Length: 69201, dtype: float64

In [40]:
area.max()

132462000.0